<center>
  <h1>DS3000</h1>
  <h1>FLA1: Vectorized Operations - Numpy</h1>
</center>

This tutorial will focus on the vectorized operations in <b>numpy</b> package. At the end of the tutorial, you'll able to confidently answer the following questions:
<ol>
<li> What are vectorized operations?
<li> How to use them?
</ol>

**Instructions:**
- It is okay if you work with another person on this FLA. Each of you should individually submit the completed file (even if it's the same file). 
- Synchronous students will complete this FLA during the live session.
- Asynchronous students will complete it by the deadline specified. If you want to collaborate with an asynchronous classmate, you will need to find them on your own (through discussion posts maybe).
- Upload your completed Notebook to Google Colab (https://colab.research.google.com/notebooks/)
- Get a shareable link to your Notebook on Colab
    * Go to Share near the top-right corner of the screen.
    * <font color='red'> **Make sure you select "Anyone with the Link Can View"** </font>
    * Copy the link
* Go to Canvas
* **Upload your completed Jupyter Notebook through the Canvas FLA link.**
* **Paste the link to your Colab Notebook in the Comments field.**
* Both are required!
<hr>



<center> 
    <h2>Part 1: Array Operations</h2>
</center>
<hr>

1. Write a code snippet to generate two 3x3 arrays, arr1 and arr2. The arrays should be randomly populated with numbers 1-5. Remember there is a method for this! Refer to the sample outputs below.

In [1]:
import numpy as np

arr1 = np.random.randint(1,6,(3,3))
arr2 = np.random.randint(1,6,(3,3))

In [2]:
arr1

array([[3, 3, 3],
       [1, 5, 5],
       [5, 3, 3]])

In [ ]:
arr2

array([[3, 2, 5],
       [2, 1, 4],
       [5, 3, 4]])

2. Go ahead and **add** these two arrays using the addition operator (+) and store the result in the arr3 variable.

In [3]:
arr3 = arr1 + arr2
arr3

array([[4, 4, 6],
       [6, 9, 8],
       [6, 5, 5]])

3. Now go ahead and **multiply** these two arrays using the multiplication operator (*) and store the result in the arr4 variable.

In [4]:
arr4 = arr1 * arr2
arr4

array([[ 3,  3,  9],
       [ 5, 20, 15],
       [ 5,  6,  6]])

4. Based on arr3 and arr4, what can you conclude about array/matrix operations in Numpy? Type your answer below:

In [8]:
# numpy is a fast and simple method of colculation over entire array instead of looping through the entire array


<center> 
    <h2>Part 2: Vectorization Tutorial</h2>
</center>
<hr>

<h2> 1. Introduction </h2>
Most of real life applications often deal with large amounts of data. So one can imagine how a computationally-suboptimal function can quickly become a bottleneck and result in high latency. 

In other words, non-optimal functions can steal away luster from your amazing code! There comes vectorization to save the day!

So what is vectorization? 
<i><p><center>"This practice of replacing explicit loops with array expressions is commonly referred to as vectorization. In general, vectorized array operations will often be one or two (or more) orders of magnitude faster than their pure Python equivalents, with the biggest impact [seen] in any kind of numerical computations." <br>~Wes McKinney (creator of Pandas package)</center></p></i>

Simply put, it is a way to code stuff without using loop statements! It is the ability to express operations over the entire array than their individual elements!

Let's look at some examples to further understand this.

<h2> 2. Examples </h2>

To demonstrate this, we will follow a simple approach: time non-vectorized and vectorized operations.
You are expected to write the non-vectorized code by following the instructions given in the corrosponding blocks.

After every example, we'll check out the time differences.

<hr>
Note: Inferences are left as an exercise for the reader.

In [6]:
import numpy as np
import time

<h3> 2.1 Square Root </h3>

<b>Given</b> -> A 1-d matrix of size 10000 <br>
<b>To-do</b> -> Calculate square root of the matrix

Execute the following cell first.

In [7]:
data = np.random.randint(low = 1, high = 10000, size = 10000)
data

array([8275, 2052, 4810, ..., 6866, 8059, 5544])

<h4>2.1.1. Non-Vectorized approach</h4>

In [9]:
'''
Here we are going to calculate the square root of each element in the given array.
Follow the instructions below.
'''

start_time = time.time() #execution start time

# COMPLETE THE CODE BELOW
# DEFINE AN EMPTY LIST 'res'
# ITERATE OVER THE 'data' VARIABLE USING FOR LOOP
# CALCULATE THE SQUARE ROOT OF EACH ELEMENT
# SAVE THE RESULTS IN 'res'

''' WRITE CODE BELOW '''
res=np.array([])
for x in data:
    res = np.append(res, x ** 0.5)
    # print(res[:20])
''' WRITE CODE ABOVE '''

end_time = time.time() #execution start time

for_loop_time_0 = end_time - start_time #time taken

print ("Time taken:\t{}".format(for_loop_time_0))

[90.96702699 45.29900661 69.35416354 85.05880319 41.94043395 42.3792402
 65.53624951 58.21511831 72.34638899 31.67017524 95.16301803 37.86819246
 91.46037393 54.39669108 48.62098312 60.02499479 52.1919534  53.57238094
 20.46948949 45.92385001]
Time taken:	0.14521098136901855


<hr>
<h4>2.1.2. Vectorized Approach</h4>
Check out how to solve the same with vectorized operations by running the following two cells:

* You don't need to write or change anything for this one. Simply execute the cells.

**To-Note**: Pay attention to the difference in execution times



In [10]:
# vector method
start_time = time.time() #execution start time

# simply calling the numpy.sqrt method
res = np.sqrt(data)

end_time = time.time() #execution end time

vector_time_0 = end_time - start_time #time taken

print ("Time taken:\t{}".format(vector_time_0))

Time taken:	0.0002770423889160156


In [11]:
print ("Vector operation is {:.2f}x faster".format(for_loop_time_0/vector_time_0))

Vector operation is 524.15x faster


<h3> 2.2 Counting numbers </h3>

<b>Given</b> -> 1-d array of 100000 elements between 1 and 999. <br>
<b>To-do</b> -> Count number of numbers greater than or equal to 500.

<hr>
Careful readers will notice how this can be applied for summing over a matrix as well.

Execute the following cell first.

In [12]:
data_1 = np.random.randint(low = 1, high = 1000, size = 100000, dtype = int)
data_1

array([916, 557, 963, ..., 756, 271, 298])

<h4>2.2.1. Non-Vectorized Approach</h4>

In [13]:
'''
Here we will count the number of numbers greater than 500
'''

start_time = time.time() #execution start time

# COMPLETE THE CODE
# INITLIAZE A 'count' VARIABLE
# ITERATE OVER THE ARRAY USING LOOP OF YOUR CHOICE
## CHECK IF THE ELEMENT IS GREATER THAN 500, IF YES INCREASE THE 'count' VARIABLE BY 1

''' WRITE CODE BELOW '''
# answer goes here
count = 0
for x in data_1:
    if x > 500:
        count += 1
''' WRITE CODE ABOVE '''

end_time = time.time() #execution end time

for_loop_time_1 = end_time - start_time #time taken

print ("{} numbers are greater than or equal to 500\nTime taken: {}".format(count, for_loop_time_1))

49948 numbers are greater than or equal to 500
Time taken: 0.051506996154785156


<h4>2.2.2. Vectorized Approach</h4>

In [14]:
# vectorized approach
start_time = time.time() #execution start time

count = np.sum(data_1 >= 500)

end_time = time.time() #execution end time

vector_time_1 = end_time - start_time #time taken
print ("{} numbers are greater than or equal to 500\nTime taken: {}".format(count, vector_time_1))

50051 numbers are greater than or equal to 500
Time taken: 0.0012001991271972656


In [15]:
print ("Vector operation is {:.2f}x faster".format(for_loop_time_1/vector_time_1))

Vector operation is 42.92x faster


<h3> 2.3 Dot Product </h3>
    
Simply put, the dot product of two arrays is the sum of the products of the corresponding elements of the two arrays. To compute the dot product of two arrays, you first perform an element-wise multiplication of the corresponding elements and then sum them up. In this question, you will practice this.

<b>Given</b> -> Two 1-d arrays of size 10000 each <br>
<b>To-do</b> -> Perform dot-product of those matrices

Execute the following cells first.


In [16]:
data_a = np.random.randint(low = 1, high = 500, size = (10000))
data_b = np.random.randint(low = 1, high = 500, size = (10000))

In [17]:
data_a

array([285, 459, 312, ..., 152, 247,   3])

In [18]:
data_b

array([377, 105, 229, ..., 463, 110, 318])

<h4>2.3.1. Non-Vectorized Approach</h4>

In [23]:
'''
Here we'll calculate the dot product of 2 arrays (sum of element-wise multiplication of 2 arrays)
'''

start_time = time.time() #execution start time

# COMPLETE THE CODE
# INITIALIZE A VARIABLE 'dot' TO HOLD THE RESULT
# ITERATE OVER ONE OF THE ARRAYs USING A FOR LOOP 
# NOTE: BOTH ARRAYS ARE SAME SIZE, SO IT WON'T MATTER WHICH ARRAY YOU ITERATE OVER
# MULTIPLY ELEMENTS AND UPDATE THE 'dot' VARIABLE

''' WRITE CODE BELOW '''
dot = [data_a[x] * data_b[x] for x in range(len(data_a))]
''' WRITE CODE ABOVE '''

end_time = time.time() #execution end time

for_loop_time_2 = end_time - start_time #time taken
print ("Dot product:\t{}\nTime taken:\t{}".format(dot, for_loop_time_2))

Dot product:	[107445, 48195, 71448, 22575, 63410, 108836, 41925, 82140, 27675, 26894, 38532, 44550, 129602, 1078, 230860, 93810, 19372, 102378, 45384, 1976, 700, 78492, 36075, 30411, 5900, 84587, 194040, 35112, 84266, 1364, 102144, 97904, 41300, 7923, 143244, 125715, 8784, 8640, 29754, 20768, 27000, 30360, 134016, 18696, 33043, 14338, 6237, 39360, 18704, 38709, 74304, 96254, 58191, 64119, 17650, 13505, 109278, 116280, 159247, 120280, 32766, 6873, 37696, 29705, 151792, 61614, 46018, 17575, 4445, 17982, 97600, 3306, 10344, 33930, 79695, 63840, 43010, 124476, 120265, 25872, 38052, 5831, 34144, 156948, 37411, 86449, 25680, 100536, 116388, 80030, 85324, 37408, 119340, 889, 36168, 57902, 8496, 33734, 106673, 7236, 39732, 16380, 13373, 163737, 22878, 55384, 100980, 52080, 80220, 24309, 151680, 36000, 62976, 4144, 52658, 55188, 309, 25840, 91455, 24016, 24409, 101480, 174336, 218562, 33909, 13032, 126280, 36876, 41223, 22148, 11252, 21450, 56160, 185712, 15708, 67980, 2814, 30687, 1748, 5885, 

<h4>2.3.2. Vectorized Approach</h4>

In [24]:
# vector method
start_time = time.time() #execution start time

dot = np.dot(data_a, data_b)

end_time = time.time() #execution end time

vector_time_2 = end_time - start_time #time taken
print ("Dot product:\t{}\nTime taken:\t{}".format(dot, vector_time_2))

Dot product:	625015076
Time taken:	0.0006871223449707031


In [25]:
print ("Vector operation is {:.2f}x faster".format(for_loop_time_2/vector_time_2))

Vector operation is 8.25x faster


<h3> 2.4 Matrix Multiplication </h3>
<b>Given</b> -> Two 2-d arrays of size 100x100 each  <br>
<b>To-do</b> -> Perform matrix multiplication

Execute the following cells first.

In [26]:
data_a = np.random.randint(low = 1, high = 1000, size = (100, 100))
data_b = np.random.randint(low = 1, high = 1000, size = (100, 100))

In [27]:
data_a

array([[647, 669, 616, ..., 193, 977, 458],
       [927, 717,  89, ..., 334, 370, 351],
       [995, 837, 195, ..., 405, 849, 299],
       ...,
       [718,  48, 394, ..., 117,  40, 643],
       [ 33, 620, 610, ..., 929, 201, 543],
       [919, 124, 181, ...,  15, 426,  44]])

In [28]:
data_b

array([[ 52, 515, 769, ..., 717,  27, 743],
       [340, 144, 147, ..., 305,  24, 827],
       [ 41,  38, 640, ..., 334, 723, 484],
       ...,
       [526, 327, 113, ..., 937, 196, 732],
       [450, 134, 723, ..., 747, 893, 488],
       [613, 948, 818, ..., 638, 376, 985]])

<h4>2.4.1. Non-Vectorized Approach</h4>

In [29]:
'''
Here we'll multiply 2 matrices. Simply run the cell.
'''
# COMPLETE CODE
start_time = time.time()

result = np.zeros((100, 100))
for i in range(len(data_a)):
    for j in range(len(data_b[0])):
        for k in range(len(data_b)):
            result[i][j] += data_a[i][k] * data_b[k][j]

end_time = time.time()
for_loop_time_3 = end_time - start_time
print ("Time taken:\t{}".format(for_loop_time_3))

Time taken:	1.3164210319519043


In [30]:
result.reshape(100, 100)

array([[24737178., 24073875., 27483383., ..., 30737775., 26320517.,
        28192083.],
       [23914385., 23752231., 25418267., ..., 28335904., 22999915.,
        27189005.],
       [25124094., 24338021., 27029705., ..., 27814861., 23378468.,
        25934719.],
       ...,
       [26950099., 24922079., 27764552., ..., 31171380., 26070051.,
        28097496.],
       [26667042., 23821296., 24719310., ..., 29942834., 23869449.,
        28211957.],
       [22889320., 23135674., 24539798., ..., 27194506., 23595066.,
        27341739.]])

<h4>2.4.2. Vectorized Approach</h4>

In [31]:
# vector operations
start_time = time.time()

res = np.dot(data_a, data_b)

end_time = time.time()

vector_time_3 = end_time - start_time
print ("Time taken:\t{}".format(vector_time_3))

Time taken:	0.0031838417053222656


In [32]:
print ("Vector operation is {:.2f}x faster".format(for_loop_time_3/vector_time_3))

Vector operation is 413.47x faster


<h2> 3. Conclusion </h2>

We see how "fast" the vector operations are! Although this is on sub-second scales, one should realize the importance of vectorized operations.

<hr>
Learn more here: https://www.pythonlikeyoumeanit.com/Module3_IntroducingNumpy/VectorizedOperations.html
